requirements: Pin werkzeug < 3.0
3.0 breaks the flask-login module with:

   File "/usr/lib/python3.11/site-packages/flask_login/utils.py", line 14, in <module>
    from werkzeug.urls import url_decode
ImportError: cannot import name 'url_decode' from 'werkzeug.urls' (/usr/lib/python3.11/site-packages/werkzeug/urls.py)

Signed-off-by: Andy Doan <andy@foundries.io>